# fly.toml app configuration file generated for mybasecampv2 on 2023-05-26T08:39:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mybasecampv2"
primary_region = "lhr"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
